# Bluetooth
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="DogRobot"
CONFIG_BT_GATT_DYNAMIC_DB=y
CONFIG_BT_MAX_CONN=1
CONFIG_BT_DEVICE_APPEARANCE=833

# Logging
CONFIG_LOG=y
CONFIG_PRINTK=y

# Console
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# System
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=32768

# FPU
CONFIG_FPU=y

# I2C Configuration
#CONFIG_I2C=y
#CONFIG_I2C_ESP32=y
#CONFIG_LOG_DEFAULT_LEVEL=3
#CONFIG_I2C_LOG_LEVEL_INF=y

# GPIO
CONFIG_GPIO=y
CONFIG_GPIO_ESP32=y

#servos
#CONFIG_PWM=y

# Force I2C bitbang mode (software I2C)
#CONFIG_I2C_BITBANG=y
#CONFIG_I2C_GPIO=y

# LED Strip (WS2812)
CONFIG_LED=y
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_SPI=y
CONFIG_SPI=y

